### ISSUE TITLE
Error while registering a user through /users/register' API path

### ISSUE THREAD

**Issue by appfobia** [cornflourblue/node-mongo-registration-login-api#1]
Unable to register a user through /users/register' API path with the following user parameter.
```javascript
{ usename: "demo",
firstName:"demo1",
lastName:"demo2",
password:"demo4"
}
```

error message is
```javascript
{
    "message": "User validation failed: lastName: Path `lastName` is required., firstName: Path `firstName` is required., hash: Path `hash` is required., username: Path `username` is required."
}
```

**Comment by darshanan24** [comment]
I guess you must be typing username spelling wrong

**Comment by appfobia** [comment]
I typed it incorrectly.
However, I tried to run the code base only using user email and password.
Now I'm facing the following issue.
Once I signup with for the first time. It is issuing a duplicate key error, when I start signing up second time. I'm still working to make your code work. 
You can find a live code base at _https://glitch.com/~quiver-stoat_
`{ MongoError: E11000 duplicate key error index: osx2.users.$username_1 dup key: { : null }
    at Function.create (/rbd/pnpm-volume/46f3a9f7-79c5-40ca-ba7b-c92c077e3752/node_modules/.registry.npmjs.org/mongodb-core/3.1.11/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/rbd/pnpm-volume/46f3a9f7-79c5-40ca-ba7b-c92c077e3752/node_modules/.registry.npmjs.org/mongodb/3.1.13/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.insert (/rbd/pnpm-volume/46f3a9f7-79c5-40ca-ba7b-c92c077e3752/node_modules/.registry.npmjs.org/mongodb/3.1.13/node_modules/mongodb/lib/operations/collection_ops.js:859:39)
    at /rbd/pnpm-volume/46f3a9f7-79c5-40ca-ba7b-c92c077e3752/node_modules/.registry.npmjs.org/mongodb-core/3.1.11/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error index: osx2.users.$username_1 dup key: { : null }',
  [Symbol(mongoErrorContextSymbol)]: {} }`

**Comment by appfobia** [comment]
Ok, actually a previously indexed parameter was there in the DB. Therefore, mongo was issuing the duplicate error. Now, the signup process is working!
Thanks for your code and write up.
It would be better if you add a caveat in the write that the user should first whitelist the route in /jwt, and then start tweaking with your existing code.
